import { useEffect, useMemo, useState } from "react";
import { FileText, Download, Sparkles, X, Loader2 } from "lucide-react";
import { useTechnologyIntelligence } from "@/hooks/useTechnologyIntelligence";
import { loadWorkspace, toggleWorkspace, signalStrength, strengthBand, fmtFunding, loadStances } from "./lib";
import { cn } from "@/lib/utils";

export default function CompassStudio() {
  const { data: techs = [] } = useTechnologyIntelligence();
  const [workspace, setWorkspace] = useState<string[]>(loadWorkspace());
  const [report, setReport] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [hypothesis, setHypothesis] = useState("");

  useEffect(() => {
    const h = () => setWorkspace(loadWorkspace());
    window.addEventListener("compass:workspace-changed", h);
    return () => window.removeEventListener("compass:workspace-changed", h);
  }, []);

  const items = useMemo(
    () => workspace.map((kid) => techs.find((t) => t.keywordId === kid)).filter(Boolean),
    [workspace, techs]
  );

  const generate = async () => {
    setGenerating(true);
    await new Promise((r) => setTimeout(r, 900)); // simulated AI synthesis
    const stances = loadStances();
    const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
    const md = [
      `# Strategic Briefing — ${date}`,
      "",
      hypothesis ? `**Hypothesis under test:** ${hypothesis}` : "*No hypothesis specified — producing an open-frame briefing.*",
      "",
      `## Executive summary`,
      `${items.length} technologies under review. Average Signal Strength: **${
        Math.round(items.reduce((a, t) => a + signalStrength(t as any), 0) / Math.max(items.length, 1))
      } / 100**. Combined tracked investment: **${fmtFunding(items.reduce((a, t: any) => a + t.totalFundingEur, 0))}**.`,
      "",
      `## Per-technology read`,
      ...items.map((t: any) => {
        const s = signalStrength(t);
        const band = strengthBand(s);
        const stance = stances[t.keywordId];
        return [
          `### ${t.name} — ${s}/100 (${band.label})`,
          stance ? `_Stance: ${stance === "bullish" ? "🟢 Bullish" : "🔴 Bearish"}_` : "",
          ``,
          `- Investment: ${fmtFunding(t.totalFundingEur)} across ${t.dealroomCompanyCount} companies`,
          `- Patents: ${t.totalPatents.toLocaleString()}`,
          `- News mentions (12mo): ${t.newsMentionCount}`,
          t.description ? `\n${t.description}` : "",
        ].join("\n");
      }),
      "",
      `---`,
      `*Generated by Compass · Preview build · Data is real, narrative is wizard-of-oz for UX validation.*`,
    ].join("\n");
    setReport(md);
    setGenerating(false);
  };

  const download = () => {
    if (!report) return;
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `compass-briefing-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-10">
      <header>
        <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Collect · Compose · Publish</p>
        <h1 className="mt-2 font-display text-3xl text-slate-100">Report Studio</h1>
        <p className="mt-2 max-w-2xl text-sm text-slate-500">
          Pull technologies into your workspace from the Briefing or any deep-dive page, frame a hypothesis,
          and generate a narrative briefing.
        </p>
      </header>

      <div className="grid gap-6 lg:grid-cols-[1fr,1.4fr]">
        {/* Workspace */}
        <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-5">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-display text-lg text-slate-100">Workspace</h2>
            <span className="text-xs text-slate-500">{items.length} items</span>
          </div>

          {items.length === 0 ? (
            <div className="rounded-lg border border-dashed border-white/10 px-4 py-12 text-center">
              <FileText className="mx-auto h-6 w-6 text-slate-700" />
              <p className="mt-3 text-sm text-slate-500">Workspace is empty.</p>
              <p className="mt-1 text-xs text-slate-600">Add items from the Briefing using the bookmark icon.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {items.map((t: any) => {
                const s = signalStrength(t);
                const band = strengthBand(s);
                return (
                  <div
                    key={t.id}
                    className="group flex items-center justify-between gap-3 rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2.5"
                  >
                    <div className="min-w-0">
                      <p className="truncate text-sm text-slate-200">{t.name}</p>
                      <p className={cn("text-[11px]", band.color)}>{band.label} · {s}/100</p>
                    </div>
                    <button
                      onClick={() => {
                        toggleWorkspace(t.keywordId);
                        setWorkspace(loadWorkspace());
                      }}
                      className="text-slate-600 opacity-0 transition-opacity group-hover:opacity-100 hover:text-slate-200"
                    >
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </div>
                );
              })}
            </div>
          )}

          <div className="mt-6 space-y-3">
            <label className="block text-xs uppercase tracking-wider text-slate-500">
              Hypothesis (optional)
            </label>
            <textarea
              value={hypothesis}
              onChange={(e) => setHypothesis(e.target.value)}
              placeholder="e.g. ‘SDV middleware will consolidate around 2 vendors by 2027’"
              className="w-full resize-none rounded-lg border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-slate-200 placeholder:text-slate-600 focus:border-cyan-400/40 focus:outline-none"
              rows={3}
            />
            <button
              onClick={generate}
              disabled={items.length === 0 || generating}
              className="flex w-full items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-cyan-400 to-indigo-400 px-4 py-2.5 text-sm font-medium text-slate-950 transition-opacity hover:opacity-90 disabled:opacity-40"
            >
              {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {generating ? "Synthesising..." : "Generate briefing"}
            </button>
          </div>
        </section>

        {/* Report preview */}
        <section className="rounded-2xl border border-white/10 bg-gradient-to-b from-white/[0.03] to-transparent p-6">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-display text-lg text-slate-100">Preview</h2>
            {report && (
              <button
                onClick={download}
                className="flex items-center gap-1.5 rounded-md border border-white/10 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/5"
              >
                <Download className="h-3.5 w-3.5" />
                Download .md
              </button>
            )}
          </div>

          {!report ? (
            <div className="flex h-96 items-center justify-center rounded-lg border border-dashed border-white/10 text-center text-sm text-slate-600">
              Generate a briefing to preview it here.
            </div>
          ) : (
            <pre className="max-h-[600px] overflow-auto whitespace-pre-wrap rounded-lg bg-black/30 p-5 text-sm leading-relaxed text-slate-300">
              {report}
            </pre>
          )}
        </section>
      </div>
    </div>
  );
}
