
UPDATE technologies SET description = CASE name
  WHEN 'Autonomous Driving' THEN 'Self-driving vehicle technology using AI, sensors, and decision-making systems to navigate without human intervention.'
  WHEN 'Autonomous Mobile Robots' THEN 'Robots capable of autonomous navigation and task execution in industrial and logistics environments.'
  WHEN 'AV Camera' THEN 'Computer vision camera systems providing object detection and scene understanding for autonomous vehicles.'
  WHEN 'AV Labeling' THEN 'Data annotation and labeling tools for training autonomous vehicle perception and AI models.'
  WHEN 'AV Radar' THEN 'Radar sensing technology for autonomous vehicles providing distance, speed, and object detection in all weather conditions.'
  WHEN 'AV Simulation' THEN 'Virtual testing and simulation platforms for validating autonomous driving algorithms and scenarios.'
  WHEN 'AV Software' THEN 'Software stacks powering autonomous vehicle decision-making, path planning, and sensor fusion.'
  WHEN 'Battery Electric Vehicle' THEN 'Fully electric vehicles powered exclusively by rechargeable battery packs with zero tailpipe emissions.'
  WHEN 'Battery Management Systems' THEN 'Electronic systems monitoring and controlling battery cell performance, health, and safety in electric vehicles.'
  WHEN 'Bidirectional Charging' THEN 'Technology enabling EVs to both charge from and discharge energy back to the grid or buildings.'
  WHEN 'Electric Mobility' THEN 'Broad ecosystem of electrically powered transportation solutions spanning vehicles, infrastructure, and services.'
  WHEN 'Electric Vehicle' THEN 'Battery-powered vehicles replacing internal combustion engines with electric drivetrains for sustainable transport.'
  WHEN 'Energy Management Systems' THEN 'Software platforms optimizing energy generation, storage, distribution, and consumption across networks.'
  WHEN 'EV Battery' THEN 'Advanced battery cell and pack technologies providing energy storage for electric vehicle propulsion.'
  WHEN 'EV Charging' THEN 'Charging infrastructure and hardware enabling electric vehicles to recharge, from home wallboxes to fast-charging stations.'
  WHEN 'EV Motor' THEN 'Electric motor and drivetrain technologies converting electrical energy into vehicle propulsion.'
  WHEN 'EV Services' THEN 'Digital services and platforms supporting EV ownership, fleet management, and charging network operations.'
  WHEN 'Fleet Management' THEN 'Software and telematics solutions for managing commercial vehicle fleets, routing, and operational efficiency.'
  WHEN 'LiDAR' THEN 'Light detection and ranging sensors creating precise 3D maps of the environment for autonomous navigation.'
  WHEN 'Logistics' THEN 'Technology solutions for freight, warehousing, and last-mile delivery optimization.'
  WHEN 'Logistics Robots' THEN 'Autonomous robotic systems for warehouse picking, sorting, and material handling in logistics operations.'
  WHEN 'Logistics Tech' THEN 'Digital platforms and tools for supply chain visibility, route optimization, and shipment tracking.'
  WHEN 'Micro Grid' THEN 'Localized energy grids that can operate independently, integrating renewables and storage for resilient power supply.'
  WHEN 'Micromobility' THEN 'Lightweight electric vehicles like e-scooters and e-bikes for short-distance urban transportation.'
  WHEN 'Mobile Energy Storage Units' THEN 'Portable battery systems providing temporary power supply for events, construction, or emergency grid support.'
  WHEN 'Renewable Energy Sources' THEN 'Clean energy generation technologies including solar, wind, and hydrogen powering sustainable mobility infrastructure.'
  WHEN 'Residential Energy Management' THEN 'Home energy optimization systems managing solar panels, batteries, EV charging, and smart appliances.'
  WHEN 'Self Adaptive Energy' THEN 'AI-driven energy systems that dynamically adjust consumption and generation patterns in real time.'
  WHEN 'Self-driving vehicles' THEN 'Vehicles equipped with full autonomy capabilities for passenger and goods transportation without a driver.'
  WHEN 'SES - Solar Energy System' THEN 'Photovoltaic systems converting sunlight into electricity for residential, commercial, and mobility applications.'
  WHEN 'SES - Stationary Energy Storage' THEN 'Fixed-location battery systems storing energy for grid stabilization, peak shaving, and renewable integration.'
  WHEN 'Shared Energy Storage' THEN 'Community-scale battery systems enabling multiple users to share stored energy resources.'
  WHEN 'Smart Cities' THEN 'Urban technology ecosystems integrating IoT, data analytics, and connected infrastructure for city management.'
  WHEN 'Smart City' THEN 'Connected urban infrastructure using sensors and data platforms to improve transport, energy, and services.'
  WHEN 'Smart Grid' THEN 'Digitally enhanced electrical grids using real-time data and automation for efficient energy distribution.'
  WHEN 'Smart Logistics' THEN 'AI and IoT-powered logistics platforms enabling predictive, automated supply chain and delivery operations.'
  WHEN 'Storage Battery Systems' THEN 'Large-scale battery technologies for industrial and grid energy storage applications.'
  WHEN 'Supply Chain' THEN 'End-to-end technology solutions for managing procurement, manufacturing, and distribution networks.'
  WHEN 'Supply Chain Management' THEN 'Digital platforms providing visibility, planning, and optimization across global supply chain operations.'
  WHEN 'Sustainability Measurement' THEN 'Tools and frameworks for tracking, reporting, and verifying environmental impact and carbon footprint.'
  WHEN 'Sustainable Mobility' THEN 'Transport solutions designed to minimize environmental impact through electrification and shared services.'
  WHEN 'Teledriving' THEN 'Remote human operation of vehicles via high-bandwidth connectivity for situations beyond autonomous capability.'
  WHEN 'Telematics' THEN 'In-vehicle communication systems transmitting real-time data on location, diagnostics, and driving behavior.'
  WHEN 'Uninterrupted Power Supply' THEN 'Backup power systems ensuring continuous electricity during grid outages for critical infrastructure.'
  WHEN 'Vehicle as Software' THEN 'Architectural paradigm treating vehicles as software-defined platforms with continuous feature updates over-the-air.'
  WHEN 'Vehicle Safety' THEN 'Active and passive safety technologies including ADAS, crash avoidance, and occupant protection systems.'
  WHEN 'Vehicle to Everything' THEN 'V2X communication technology enabling vehicles to exchange data with infrastructure, other vehicles, and networks.'
  WHEN 'Vehicle to Grid' THEN 'Technology allowing EVs to feed stored energy back to the power grid, supporting demand response and grid stability.'
  ELSE description
END
WHERE description IS NULL OR name IN (
  'Electric Vehicle', 'Smart Recharging'
);
